/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hneen.myoop.GUI;

import com.hneen.myoop.DB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author hneen
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
String pass;
String user;
public employee(String username,String password){
    initComponents();
    showEmployee_info(username,password);
    user=username;
    pass=password;
}
    public employee() {
        initComponents();

    }
void showEmployee_info(String username,String password){
    DB conn=new DB();
    Connection dbconn=conn.connectDB();
    ResultSet emp_ifo=null;
    PreparedStatement st=null;
    ResultSet res=null;
    PreparedStatement st1=null;
    try {
        int emp_id=-1;
         st = (PreparedStatement)
                dbconn.prepareStatement("select * from account where username = ? and password =? ");
        st.setString(1, username);
        st.setString(2, password);
         res = st.executeQuery();
        if (res.next()){
            emp_id=res.getInt("person_id");
             st1 = (PreparedStatement)
                    dbconn.prepareStatement("select * from employee where Employee_id = ? ");
            st1.setInt(1,emp_id);
             emp_ifo=st1.executeQuery();
            if (emp_ifo.next()){
                ID_textFiled.setText(emp_ifo.getString("Employee_id"));
                Name_Label.setText(emp_ifo.getString("Employee_name"));
                Eamil_jLabel.setText(emp_ifo.getString("Employee_Email"));
                AdderessjLabel.setText(emp_ifo.getString("Employee_address"));
            }

        }
    }catch (Exception e){
        e.printStackTrace();
    }finally {
        try {
            dbconn.close();
            emp_ifo.close();
            st.close();
            st1.close();
            res.close();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutBotoms = new javax.swing.JButton();
        Add_itemsButton = new javax.swing.JButton();
        delete_itemsButton = new javax.swing.JButton();
        Add_cdButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        view_ItemsBotoms1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ID_textFiled = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name_Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Eamil_jLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdderessjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 244, 248));

        jPanel1.setBackground(new java.awt.Color(255, 114, 76));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hneen\\Documents\\NetBeansProjects\\project_oop2\\src\\main\\icons\\dashboard.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("employees dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        LogOutBotoms.setBackground(new java.awt.Color(253, 191, 80));
        LogOutBotoms.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        LogOutBotoms.setForeground(new java.awt.Color(42, 44, 65));
        LogOutBotoms.setText("LogOut");
        LogOutBotoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBotomsActionPerformed(evt);
            }
        });

        Add_itemsButton.setBackground(new java.awt.Color(253, 191, 80));
        Add_itemsButton.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Add_itemsButton.setForeground(new java.awt.Color(42, 44, 65));
        Add_itemsButton.setText("Add Books");
        Add_itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_itemsButtonActionPerformed(evt);
            }
        });

        delete_itemsButton.setBackground(new java.awt.Color(253, 191, 80));
        delete_itemsButton.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        delete_itemsButton.setForeground(new java.awt.Color(42, 44, 65));
        delete_itemsButton.setText("Delete Items");
        delete_itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_itemsButtonActionPerformed(evt);
            }
        });

        Add_cdButton1.setBackground(new java.awt.Color(253, 191, 80));
        Add_cdButton1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Add_cdButton1.setForeground(new java.awt.Color(42, 44, 65));
        Add_cdButton1.setText("Add CD(E-Books)");
        Add_cdButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_cdButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Text", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Welcome");

        view_ItemsBotoms1.setBackground(new java.awt.Color(253, 191, 80));
        view_ItemsBotoms1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        view_ItemsBotoms1.setForeground(new java.awt.Color(42, 44, 65));
        view_ItemsBotoms1.setText("view Items");
        view_ItemsBotoms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ItemsBotoms1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 102));
        jLabel4.setText("ID:");

        ID_textFiled.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        ID_textFiled.setForeground(new java.awt.Color(0, 51, 153));
        ID_textFiled.setText("id");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 102));
        jLabel5.setText("Name:");

        Name_Label.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        Name_Label.setForeground(new java.awt.Color(0, 51, 153));
        Name_Label.setText("name");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 102));
        jLabel6.setText("Email:");

        Eamil_jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        Eamil_jLabel.setForeground(new java.awt.Color(0, 51, 153));
        Eamil_jLabel.setText("email");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 102));
        jLabel7.setText("Address:");

        AdderessjLabel.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        AdderessjLabel.setForeground(new java.awt.Color(0, 51, 153));
        AdderessjLabel.setText("address");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(421, 421, 421)
                            .addComponent(delete_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(Add_cdButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(LogOutBotoms, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(Add_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(view_ItemsBotoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(207, 207, 207))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_textFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdderessjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eamil_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_textFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Eamil_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AdderessjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_ItemsBotoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_cdButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOutBotoms, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBotomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBotomsActionPerformed
        // TODO add your handling code here:
        dispose();
        Login d= new Login();
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_LogOutBotomsActionPerformed

    private void Add_itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_itemsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Books d= new Add_Books(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_Add_itemsButtonActionPerformed

    private void delete_itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_itemsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Delete_Items d= new Delete_Items(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_delete_itemsButtonActionPerformed

    private void Add_cdButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_cdButton1ActionPerformed
        // TODO add your handling code here:
                      dispose();
        Add_Cd d=new Add_Cd(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_Add_cdButton1ActionPerformed

    private void view_ItemsBotoms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_ItemsBotoms1ActionPerformed
        // TODO add your handling code here:
          dispose();
        view_Books d= new view_Books(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_view_ItemsBotoms1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cdButton1;
    private javax.swing.JButton Add_itemsButton;
    private javax.swing.JLabel AdderessjLabel;
    private javax.swing.JLabel Eamil_jLabel;
    private javax.swing.JLabel ID_textFiled;
    private javax.swing.JButton LogOutBotoms;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JButton delete_itemsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton view_ItemsBotoms1;
    // End of variables declaration//GEN-END:variables
}
