/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hneen.myoop.GUI;

/**
 *
 * @author hneen
 */
public class manager_dord extends javax.swing.JFrame {

    /**
     * Creates new form manager_dord
     */
    String user=null;
    String pass=null;
    public manager_dord()
    {
        initComponents();
    }
    public manager_dord(String user,String pass)
    {initComponents();
        this.user=user;
        this.pass=pass;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogOutBotoms = new javax.swing.JButton();
        Add_itemsButton = new javax.swing.JButton();
        Add_cdButton1 = new javax.swing.JButton();
        delete_itemsButton = new javax.swing.JButton();
        view_ItemsBotoms1 = new javax.swing.JButton();
        Employee_Button1 = new javax.swing.JButton();
        orders_summaryButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 244, 248));

        jPanel3.setBackground(new java.awt.Color(255, 114, 76));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hneen\\Documents\\NetBeansProjects\\project_oop2\\src\\main\\icons\\dashboard.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manager dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );

        LogOutBotoms.setBackground(new java.awt.Color(253, 191, 80));
        LogOutBotoms.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        LogOutBotoms.setForeground(new java.awt.Color(42, 44, 65));
        LogOutBotoms.setText("LogOut");
        LogOutBotoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBotomsActionPerformed(evt);
            }
        });

        Add_itemsButton.setBackground(new java.awt.Color(253, 191, 80));
        Add_itemsButton.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Add_itemsButton.setForeground(new java.awt.Color(42, 44, 65));
        Add_itemsButton.setText("Add Books");
        Add_itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_itemsButtonActionPerformed(evt);
            }
        });

        Add_cdButton1.setBackground(new java.awt.Color(253, 191, 80));
        Add_cdButton1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Add_cdButton1.setForeground(new java.awt.Color(42, 44, 65));
        Add_cdButton1.setText("Add CD(E-Books)");
        Add_cdButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_cdButton1ActionPerformed(evt);
            }
        });

        delete_itemsButton.setBackground(new java.awt.Color(253, 191, 80));
        delete_itemsButton.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        delete_itemsButton.setForeground(new java.awt.Color(42, 44, 65));
        delete_itemsButton.setText("Delete Items");
        delete_itemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_itemsButtonActionPerformed(evt);
            }
        });

        view_ItemsBotoms1.setBackground(new java.awt.Color(253, 191, 80));
        view_ItemsBotoms1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        view_ItemsBotoms1.setForeground(new java.awt.Color(42, 44, 65));
        view_ItemsBotoms1.setText("view Items");
        view_ItemsBotoms1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ItemsBotoms1ActionPerformed(evt);
            }
        });

        Employee_Button1.setBackground(new java.awt.Color(253, 191, 80));
        Employee_Button1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Employee_Button1.setForeground(new java.awt.Color(0, 0, 0));
        Employee_Button1.setText("Manage Employees Information");
        Employee_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Button1ActionPerformed(evt);
            }
        });

        orders_summaryButton2.setBackground(new java.awt.Color(253, 191, 80));
        orders_summaryButton2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        orders_summaryButton2.setForeground(new java.awt.Color(0, 0, 0));
        orders_summaryButton2.setText("orders summary");
        orders_summaryButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_summaryButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(view_ItemsBotoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(LogOutBotoms, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(delete_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Add_cdButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Add_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(orders_summaryButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Employee_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Employee_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(orders_summaryButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_cdButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOutBotoms, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_ItemsBotoms1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBotomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBotomsActionPerformed
        // TODO add your handling code here:
        dispose();
        Login d= new Login();
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_LogOutBotomsActionPerformed

    private void Add_itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_itemsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Books d= new Add_Books(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_Add_itemsButtonActionPerformed

    private void Add_cdButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_cdButton1ActionPerformed
        // TODO add your handling code here:
        if (user!=null && pass!=null){
        dispose();
        Add_Cd d = new Add_Cd(user, pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }
    }//GEN-LAST:event_Add_cdButton1ActionPerformed

    private void delete_itemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_itemsButtonActionPerformed
        // TODO add your handling code here:
        if (pass!=null && user!=null) {
            dispose();
            Delete_Items d = new Delete_Items(user, pass);
            d.setTitle("dashbord");
            d.setVisible(true);
        }
    }//GEN-LAST:event_delete_itemsButtonActionPerformed

    private void view_ItemsBotoms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_ItemsBotoms1ActionPerformed
        // TODO add your handling code here:

        if (pass!=null && user!=null) {
            dispose();
            view_Books d = new view_Books(user, pass);
            d.setTitle("dashbord");
            d.setVisible(true);
        }
    }//GEN-LAST:event_view_ItemsBotoms1ActionPerformed

    private void orders_summaryButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_summaryButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        orders_summary d= new orders_summary(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_orders_summaryButton2ActionPerformed

    private void Employee_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Button1ActionPerformed
        // TODO add your handling code here:
          dispose();
        Employee_update d= new Employee_update(user,pass);
        d.setTitle("dashbord");
        d.setVisible(true);
    }//GEN-LAST:event_Employee_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_dord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_dord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_dord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_dord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_dord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cdButton1;
    private javax.swing.JButton Add_itemsButton;
    private javax.swing.JButton Employee_Button1;
    private javax.swing.JButton LogOutBotoms;
    private javax.swing.JButton delete_itemsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton orders_summaryButton2;
    private javax.swing.JButton view_ItemsBotoms1;
    // End of variables declaration//GEN-END:variables
}
