/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hneen.myoop.GUI;

import com.hneen.myoop.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hneen
 */
public class singUp extends javax.swing.JFrame {

    /**
     * Creates new form singUp
     */
    public singUp() {
        initComponents();
        user_buttonGroup1.add(customer_RadioButton1);
        user_buttonGroup1.add(Employee_RadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_TextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Emali_TextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usernameTextField4 = new javax.swing.JTextField();
        passwordTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        customer_RadioButton1 = new javax.swing.JRadioButton();
        Employee_RadioButton2 = new javax.swing.JRadioButton();
        singup_Button1 = new javax.swing.JButton();
        Login_Button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 248));

        jPanel2.setBackground(new java.awt.Color(253, 191, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hneen\\Documents\\NetBeansProjects\\project_oop2\\src\\main\\icons\\add-user.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign Up Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Emali:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Username:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");

        customer_RadioButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        customer_RadioButton1.setForeground(new java.awt.Color(102, 102, 102));
        customer_RadioButton1.setText("customer");

        Employee_RadioButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Employee_RadioButton2.setForeground(new java.awt.Color(102, 102, 102));
        Employee_RadioButton2.setText("Employee");

        singup_Button1.setBackground(new java.awt.Color(0, 153, 204));
        singup_Button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        singup_Button1.setForeground(new java.awt.Color(255, 255, 255));
        singup_Button1.setText("Sing Up");
        singup_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singup_Button1ActionPerformed(evt);
            }
        });

        Login_Button2.setBackground(new java.awt.Color(0, 153, 204));
        Login_Button2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Login_Button2.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button2.setText("Log In");
        Login_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(name_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(Emali_TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(addressTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(25, 25, 25)
                                .addComponent(usernameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(passwordTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customer_RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Login_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singup_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Employee_RadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emali_TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_RadioButton1)
                    .addComponent(Employee_RadioButton2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singup_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singup_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singup_Button1ActionPerformed
        // TODO add your handling code here:
        String name=name_TextField1.getText();
        String address=addressTextField3.getText();
        String emile=Emali_TextField2.getText();
        String username=usernameTextField4.getText();
        String password=passwordTextField5.getText();

        if(name.isEmpty() || password.isEmpty() || address.isEmpty() || emile.isEmpty() || username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //start the login process
           if (customer_RadioButton1.isSelected() || Employee_RadioButton2.isSelected()){
                if (EmailCheck(emile)) {
                    usersingup(name, address, emile, username, password);
                }
            }else {
               JOptionPane.showMessageDialog(this, "Are Customer or Employee? Select one !","Error", JOptionPane.ERROR_MESSAGE);

           }
        }
    }//GEN-LAST:event_singup_Button1ActionPerformed

    private void Login_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Button2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login d= new Login();
        d.setTitle("Longin");
        d.setVisible(true);
    }//GEN-LAST:event_Login_Button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singUp().setVisible(true);
            }
        });
    }
    private void  usersingup (String name, String address,String email,String username, String password){
        DB t=new DB();
        Connection dbconn=t.connectDB();
        int last_id=0;
        PreparedStatement st1=null;
        PreparedStatement st=null;
        PreparedStatement insert_id=null;
        PreparedStatement id_p=null;
        ResultSet resultSet=null;
        try {
             id_p=(PreparedStatement) dbconn.prepareStatement("SELECT * FROM person");
             resultSet=id_p.executeQuery();

           while (resultSet.next()){
                    last_id = resultSet.getInt("id");
            }

            if (customer_RadioButton1.isSelected()){
                int id=last_id+1;
                 insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
                insert_id.setInt(1,id);
                int res =insert_id.executeUpdate();
                if (res==1){
                     st = (PreparedStatement) dbconn.prepareStatement("insert into customer(coustomer_id,coustomer_name ,coustomer_address ,coustomer_Email) values (?,?,?,?)  ");
                    st.setInt(1, id);
                    st.setString(2, name);
                    st.setString(3, address);
                    st.setString(4, email);
                    int res2 = st.executeUpdate();
                    if (res2 == 1) {
                         st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password,person_id,rule) values (?,?,?,?)");
                        st1.setString(1, username);
                        st1.setString(2, password);
                        st1.setInt(3, id);
                        st1.setString(4, "c");
                        int res1 = st1.executeUpdate();
                        if (res1==1)
                        JOptionPane.showMessageDialog(this, "customer Added", "done!", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
            else  if (Employee_RadioButton2.isSelected()){
                int id=last_id+1;
                 insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
                insert_id.setInt(1,id);
                int res =insert_id.executeUpdate();
                if (res==1){
                     st = (PreparedStatement) dbconn.prepareStatement("insert into employee(Employee_id,Employee_name ,Employee_address ,Employee_Email,supervise_id) values (?,?,?,?,4)  ");
                    st.setInt(1, id);
                    st.setString(2, name);
                    st.setString(3, address);
                    st.setString(4, email);
                    int res2 = st.executeUpdate();
                    if (res2 == 1) {
                         st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password,person_id,rule) values (?,?,?,?)");
                        st1.setString(1, username);
                        st1.setString(2, password);
                        st1.setInt(3, id);
                        st1.setString(4, "e");
                        int res1 = st1.executeUpdate();
                        if (res1==1)
                            JOptionPane.showMessageDialog(this, "Employee Added", "done!", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }

        }catch (Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error in adding","Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            try {
                dbconn.close();
                insert_id.close();
                resultSet.close();
                id_p.close();
                st.close();
                st1.close();

            }catch (SQLException e){
                e.printStackTrace();
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emali_TextField2;
    private javax.swing.JRadioButton Employee_RadioButton2;
    private javax.swing.JButton Login_Button2;
    private javax.swing.JTextField addressTextField3;
    private javax.swing.ButtonGroup user_buttonGroup1;
    private javax.swing.JRadioButton customer_RadioButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name_TextField1;
    private javax.swing.JTextField passwordTextField5;
    private javax.swing.JButton singup_Button1;
    private javax.swing.JTextField usernameTextField4;
    // End of variables declaration//GEN-END:variables
    public boolean EmailCheck(String Email){
boolean emailCheck=false;
        if(Email.contains("@")){
            if (Email.contains(".com")) {
                emailCheck = true;
            }
            else {
                JOptionPane.showMessageDialog(this, "Incorrect Email Please Re-Enter Email","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else  {
            JOptionPane.showMessageDialog(this, "Incorrect Email Please Re-Enter Email","Error", JOptionPane.ERROR_MESSAGE);
        }
        return emailCheck;
    }

}
